// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDqz3CBAPFAOhGtSH0kt8ycYfi-t_23pk',
    appId: '1:654220725691:web:946be90fd5e5ba0755c89e',
    messagingSenderId: '654220725691',
    projectId: 'recipe-app-d5b80',
    authDomain: 'recipe-app-d5b80.firebaseapp.com',
    storageBucket: 'recipe-app-d5b80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPfWX2gpvYLp57IZTxnpTclwaMSfH51pQ',
    appId: '1:654220725691:android:baead1b81494ccec55c89e',
    messagingSenderId: '654220725691',
    projectId: 'recipe-app-d5b80',
    storageBucket: 'recipe-app-d5b80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsYCSj2C6J_p_7H_itOf0BHoGG6gV4c-w',
    appId: '1:654220725691:ios:8d6b588c59b3e5ad55c89e',
    messagingSenderId: '654220725691',
    projectId: 'recipe-app-d5b80',
    storageBucket: 'recipe-app-d5b80.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsYCSj2C6J_p_7H_itOf0BHoGG6gV4c-w',
    appId: '1:654220725691:ios:8d6b588c59b3e5ad55c89e',
    messagingSenderId: '654220725691',
    projectId: 'recipe-app-d5b80',
    storageBucket: 'recipe-app-d5b80.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDqz3CBAPFAOhGtSH0kt8ycYfi-t_23pk',
    appId: '1:654220725691:web:1f4239da35db4c5555c89e',
    messagingSenderId: '654220725691',
    projectId: 'recipe-app-d5b80',
    authDomain: 'recipe-app-d5b80.firebaseapp.com',
    storageBucket: 'recipe-app-d5b80.appspot.com',
  );
}
